name: filescope
description: "A professional file manager application."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Filesystem & Permissions
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  path: ^1.9.0 

  # Utility
  intl: ^0.19.0
  open_file: ^3.3.2
 ## disk_space: 0.2.1      # UPDATED this line from 0.2.1
  fl_chart: ^0.68.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: false # UPDATED this line from true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true